In [ ]:
import numpy as np
#1d
a1 = np.array( [1,2,3,4,5] )
print (a1.ndim)

#2d
a2 = np.array([[1,2,3] , [4,5,6]])

print (a2.ndim)


#3
a3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2
])


1
2



**Array attributes**

In [ ]:
# dimension
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)


#data type
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


#size
print(a1.size)
print(a2.size)
print(a3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


**ndarray data type**

In [ ]:

arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


In [ ]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


**selecting a data type for an array**


In [ ]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)




arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2],dtype=np.float64)
print(arr.dtype)
print(arr)

int16
[  1   2 300]
int32
float64
[1.  2.  3.2]


**ndarray creation from existing data**

In [ ]:
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [ ]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [ ]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [ ]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [ ]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [ ]:

#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [ ]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


**array creation with random values**

In [ ]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.57128463 0.09251975 0.79136815]
 [0.96192157 0.41670521 0.6835917 ]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [ ]:

# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[7 3 8]
 [7 9 2]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [ ]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[76.25219814 91.89505763 91.21506894 80.68641632]
  [55.21052012 91.21631253 99.69402295 76.02923859]
  [91.93466725 72.50380959 70.45852371 75.68480006]]

 [[55.27752721 53.89024181 58.61449847 79.05244231]
  [95.10594721 79.44111572 69.88700224 87.44046453]
  [91.49055881 79.28394598 57.00097407 94.53618643]]

 [[65.16885747 74.94975673 96.27391179 61.65120617]
  [87.59745418 86.13644135 88.46343183 95.54374288]
  [67.08387979 81.10109515 83.90892922 69.2836626 ]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


**array creation with range functions**

In [ ]:
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [ ]:

# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


**indexing and slicing**

In [ ]:
#indexing

print(a1)
print(a2)

# arr1[2] = 100

# print(arr1)
a2[0][2]= 100

print(a2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [ ]:
#slicing
#1d = a1[start:end:step]

a1_mod = a1[1:4].copy()
a1[1] = 2


a1_mod[2] = 200
print(a1_mod)
print(a1)

[  2   3 200]
[1 2 3 4 5]


In [ ]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(a2)

#getting a row

row_0 = a2[0:1 ,]

row_1= a2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = a2[:: ,0:1]
col_1 = a2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = a2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


**Advanced Indexing**

In [ ]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [ ]:
print(a2)
print(a2[[0,1] , [1,2]])

# boolean kono kichu diye
# print(a2[a1>1]) # Removed this line as it caused an IndexError
a2[a2>2] = 0

print(a2)

[[  1   2 100]
 [  4   5   6]]
[2 6]
[[1 2 0]
 [0 0 0]]


In [ ]:
print(a2)

[[1 2 0]
 [0 0 0]]


In [ ]:
rr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration
print(a3)
for i in np.nditer(a3):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6


**Moduel 12**

In [ ]:
import numpy as np

arr = np.random.randint(1 ,100 , size =(10,5)) # sample - 10 , feature - 5

arr.shape

(10, 5)

In [ ]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[ 1, 99, 23, 32, 33, 72, 84, 49,  1, 19],
       [57, 51, 21, 40, 63, 86,  7, 14, 16, 18],
       [27, 80, 40, 92, 90, 40, 13, 92, 77, 72],
       [ 9, 30, 37, 71, 91, 16, 65, 63, 33, 47],
       [22, 71, 42, 38, 47, 38, 73, 43, 49, 20]])

In [ ]:

flatten = b.flatten()
print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b,order= 'C')

print(column_wise_flattening)

1
[ 1 99 23 32 33 72 84 49  1 19 57 51 21 40 63 86  7 14 16 18 27 80 40 92
 90 40 13 92 77 72  9 30 37 71 91 16 65 63 33 47 22 71 42 38 47 38 73 43
 49 20]


In [ ]:

a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))

**concatenate**

In [ ]:
con_row = np.concatenate((a,b),axis=0) # row wise

print(con_row)

con_col = np.concatenate((a,b), axis = 1) # column wise

print(con_col)

[[ 1  2  7]
 [ 5  4  7]
 [23 25 23]
 [27 24 26]]
[[ 1  2  7 23 25 23]
 [ 5  4  7 27 24 26]]


**arithmetic operator and mathematical functions**

In [ ]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)


[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [ ]:
# mathematical function

# trigonometry

# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [ ]:

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [ ]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumsum(x)
print(cumul)

134
[ 10  18  34 134]


**Logical Function**

In [ ]:

# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


**Sorting**

In [ ]:

#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)


[ 10   8  16 100]
[  8  10  16 100]


In [ ]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [ ]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


**Searching**

In [ ]:
# np.where( condition , x , y ) if true x , otherwise replace with y

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [ ]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [ ]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


***counting in ndarray***

In [ ]:

a = np.random.randint(1 ,100 , size =(100,))
print(a)

[ 1 69 96 64 65 50 46 88 59 57 23 66 83 57 72 80 86 84 74 36 58 52 47 33
 23 79 70 81 69 73 71 90 19 65 65 20 14  9 91 26 22 98 79 62 74 17 17 56
 83 26 23 93 23 76 29 51 34 35 42 71 64  5 81 11 69 61 79 30 94 45 94 40
 89 23 70 47  3  2 14 82 98 30 66 70 64 51 40 40 60 77 14 12 54 33 62 32
  7 11 89 80]


**statistical function**

In [ ]:
#data load

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data)

FileNotFoundError: student_scores.csv not found.

In [ ]:
# statistics
math_marks = data[::,:1]

print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

NameError: name 'data' is not defined

**linear algebra**

In [ ]:

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))


#

[[ 58  64]
 [139 154]]
17


In [ ]:

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
